const TWITTER_TOKENS = {
  TWITTER_CONSUMER_KEY: "xT74Yw9QnUnEO6m2hpgGM60Ia",
  TWITTER_CONSUMER_SECRET: "o1nAucaOcPruOEv53Al6oFbhj91pX74Bi3LIxYs1I8UGRCOd5m",
  TWITTER_ACCESS_TOKEN: "1338399579008450561-BfAO7xt0mewqpT5upLjd4ygrwHeLUw",
  TWITTER_ACCESS_TOKEN_SECRET: "xMKRDZwyGKxPOB2U536BBHvDktH9TfyWiMb6nCASZkYgF"
};

const SESSION = {
  COOKIE_KEY: "thisappisawesome"
};

const ENV = process.env.NODE_ENV;

const SERVER_URL =
  ENV === "production"
    ? "https://twitter-helpdesk-pt.herokuapp.com"
    : "http://localhost:5000";

const SOCKET_URL = "127.0.0.1";

const SOCKET_PORT = 5001;

const JWT_SECRET = "7BAFC9A846BA37D5BF818B43BC7E83EAA6B9C97D40BF95BC89835028ED3A3CEE";

const ERROR_CODES = {
  NOT_FOUND: "NOT_FOUND",
  ALREADY_EXISTS: "ALREADY_EXISTS",
  INVALID_AUTH: "INVALID_AUTH",
  INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
  VALIDATION_ERROR: "VALIDATION_ERROR",
  NOT_AUTHORIZED: "NOT_AUTHORIZED"
};

const KEYS = {
  ...TWITTER_TOKENS,
  ...SESSION,
  JWT_SECRET,
  ERROR_CODES,
  SERVER_URL,
  SOCKET_URL,
  SOCKET_PORT,
  ENV
};

module.exports = KEYS;
